Repository ropensci/dev_guide, pull requests merged in 2024-12, with the labels that each got.

#851 Add review for Portuguese translation of `softwarereview_reviewer.pt.Rmd`
  softwarereview_reviewer.pt.Rmd
Labels: Tradução, ready-to-be-merge

#856 R1 to Add PT-BR automatic translation softwarereview_author.pt.Rmd
  softwarereview_author.pt.Rmd
Labels: Tradução, under-review

#820 Add PT-BR automatic translation softwarereview_author.pt.Rmd
  softwarereview_author.pt.Rmd
Labels: Tradução, ready-to-be-merge

#850 Add first review for `softwarereview_editor_management.Rmd`
  softwarereview_editor_management.pt.Rmd
Labels: Tradução, need-second-review

#817 Add PT-BR automatic translation softwarereview_editor_management.pt.Rmd
  softwarereview_editor_management.pt.Rmd
Labels: Tradução, ready-to-be-merge
