Repository ropensci/dev_guide, pull requests merged in 2025-03, with the labels that each got.

#867 marketing tips
  maintenance_marketing.Rmd
  maintenance_marketing.es.Rmd
  maintenance_marketing.pt.Rmd
Labels: content :page_with_curl:

#863 default branch should not be "master"
  booknews.Rmd
  pkg_building.Rmd
  pkg_building.es.Rmd
Labels: content :page_with_curl:

#878 Add rule about 1 pkg at a time
  booknews.Rmd
  softwarereview_author.Rmd
  softwarereview_author.es.Rmd
  softwarereview_author.pt.Rmd
Labels: needs-translation-review

#818 Add PT-BR automatic translation softwarereview_reviewer.pt.Rmd
  softwarereview_reviewer.pt.Rmd
Labels: Tradução, ready-to-be-merge

#858 R1 to Pkg_ci.pt.Rmd-pt-auto
  pkg_ci.pt.Rmd
Labels: Tradução, need-second-review

#772 Add PT-BR automatic translation maintenance_evolution.Rmd
  maintenance_evolution.pt.Rmd
Labels: Tradução, ready-to-be-merge

#866 add guidance for wrapping external software
  pkg_building.Rmd
  pkg_building.es.Rmd
Labels: needs-translation-review

#884 Bundled code authorship for #873
  booknews.Rmd
  pkg_building.Rmd
  pkg_building.es.Rmd
Labels: needs-translation-review

#891 Add note about dev status of dependencies for #881
  booknews.Rmd
  pkg_building.Rmd
  pkg_building.es.Rmd
Labels: needs-translation-review

#855 R1 Softwarereview_editor.pt.Rmd-pt-auto
  softwarereview_editor.pt.Rmd
Labels: Tradução, need-second-review, under-review

#859 R1 to Softwarereview_policies.pt.Rmd-pt-auto
  softwarereview_policies.pt.Rmd
Labels: Tradução, need-second-review
