Repository ropensci/dev_guide, pull requests merged in 2025-04, with the labels that each got.

#862 Add details for MEE process
  booknews.Rmd
  softwarereview_author.Rmd
  softwarereview_author.es.Rmd
  softwarereview_author.pt.Rmd
  softwarereview_editor.Rmd
  softwarereview_editor.es.Rmd
  softwarereview_editor.pt.Rmd
Labels: content :page_with_curl:, ro-hackathon-2025, needs-translation-review

#895 Add link to new pkgcheck test environment vignette to close #589
  booknews.Rmd
  softwarereview_author.Rmd
  softwarereview_author.es.Rmd
  softwarereview_author.pt.Rmd
Labels: needs-translation-review

#823 Add PT-BR automatic translation pkg_security.pt.Rmd
  pkg_security.pt.Rmd
Labels: Tradução, need-second-review, ro-hackathon-2025

#824 Add PT-BR automatic translation pkg_ci.pt.Rmd
  pkg_ci.pt.Rmd
Labels: Tradução, ready-to-be-merge, ro-hackathon-2025

#821 Add PT-BR automatic translation softwarereview_policies.pt.Rmd
  softwarereview_policies.pt.Rmd
Labels: Tradução, need-second-review, under-review, ro-hackathon-2025

#894 add how to deprecate data
  booknews.Rmd
  maintenance_evolution.Rmd
  maintenance_evolution.es.Rmd
  maintenance_evolution.pt.Rmd
Labels: needs-translation-review

#886 document drawbacks of renaming widely used package
  booknews.Rmd
  maintenance_evolution.Rmd
  maintenance_evolution.es.Rmd
  maintenance_evolution.pt.Rmd
Labels: needs-translation-review
